version: 2

build:
  os: "ubuntu-24.04"
  tools:
    python: "3.12"
  jobs:
    post_create_environment:
      - python -m pip install sphinx_rtd_theme

python:
  install:
    - requirements: docs/source/requirements.txt

sphinx:
  configuration: docs/source/conf.py