domain_path: /home/george/repos/aimbot/prj/tpg_vdma/vitis/tpg_vdma_platform/export/tpg_vdma_platform/sw/standalone_ps7_cortexa9_0
app_src_dir: /tools/Xilinx/2025.2/Vitis/data/embeddedsw/lib/sw_apps/empty_application
template: empty_application
lang: c
